#!/bin/bash
#
echo ""
echo "You are about to add all files from the "
echo "current directory to your Git checkin index,"
echo "commit them and push to your Git server."
echo ""
echo "Please enter your commit comment:"
read -e COMMENT
git add .
git commit -m "$COMMENT"
git push
